In [2]:
import numpy as np

In [3]:
import numpy as np
new_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(new_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
n3=np.zeros((10,10))
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
n1=np.full((3,3),55)
n1

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [6]:
n1=np.arange(50,101)
n1

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [22]:
n1=np.arange(50,100,500)
n1

array([50])

In [7]:

np.random.randint(100,200,10)

array([197, 195, 137, 153, 166, 172, 164, 113, 183, 142])

In [8]:
#checking the shape of NumPy arrays

In [9]:
n1=np.array([[1,2,3],[4,5,6]])
n1.shape


(2, 3)

In [11]:
n1.shape=(3,2)
n1.shape

(3, 2)

In [16]:
import numpy as np
n1=np.array([[1,2,3,4],[4,3,2,1]])
print(n1)

[[1 2 3 4]
 [4 3 2 1]]


In [17]:
n1.shape=(4,2)
n1

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [19]:
n1.shape=(8,1)
n1

array([[1],
       [2],
       [3],
       [4],
       [4],
       [3],
       [2],
       [1]])

In [ ]:
#joining NumPy Arrays

In [20]:
n1=np.array([2,3,4])
n2=np.array([5,6,7])
np.vstack((n1,n2))

array([[2, 3, 4],
       [5, 6, 7]])

In [21]:
np.hstack((n1,n2))

array([2, 3, 4, 5, 6, 7])

In [22]:
np.column_stack((n1,n2))

array([[2, 5],
       [3, 6],
       [4, 7]])

In [ ]:
#Numpy Intersection and Difference

In [23]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([40,50,60,70,80,90])
np.intersect1d(n1,n2)


array([40, 50, 60])

In [24]:
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [25]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [ ]:
# Addition of NumPy Arrays

In [26]:
n1=np.array([10,30])
n2=np.array([40,50])
np.sum([n1,n2])


130

In [28]:
np.sum([n1,n2],axis=0)


array([50, 80])

In [29]:
np.sum([n1,n2],axis=1)

array([40, 90])

In [ ]:
#basic addition substraction mul and division

In [30]:
n1=np.array([40,50,60])
n1

array([40, 50, 60])

In [31]:
n1+5

array([45, 55, 65])

In [32]:
n1-5

array([35, 45, 55])

In [33]:
n1*5

array([200, 250, 300])

In [34]:
n1/5

array([ 8., 10., 12.])

In [ ]:
#NumPy Math Functions

In [35]:
n1=np.random.randint(1,50,10)
n1

array([39,  1, 14, 41, 20, 46, 19, 35, 20, 37])

In [36]:
np.mean(n1)

27.2

In [37]:
np.median(n1)

27.5

In [38]:
np.std(n1)

13.68064325973015